import 'package:flutter_gen/gen_l10n/app_localizations.dart';

Map<String, List<String>> getTopicsData(AppLocalizations l10n) {
  return {
    l10n.category_business: [
      l10n.topic_stocks_investments,
      l10n.topic_personal_finance,
      l10n.topic_borsavefon,
      l10n.topic_opportunities_marketplace,
      l10n.topic_real_estate,
      l10n.topic_finanzen,
      l10n.topic_business_news,
      l10n.topic_crypto,
      l10n.topic_wallstreetbets,
      l10n.topic_startup_entrepreneurship,
    ],
    l10n.category_education: [
      l10n.topic_high_schoolers,
      l10n.topic_school_education,
      l10n.topic_odtu,
      l10n.topic_career,
      l10n.topic_abroad_universities,
      l10n.topic_turkish_learning,
      l10n.topic_teaching,
      l10n.topic_remote_work,
      l10n.topic_sysadmin,
      l10n.topic_jobs,
    ],
    l10n.category_humanities: [
      l10n.topic_kamalizm,
      l10n.topic_law,
      l10n.topic_historical_stuff,
      l10n.topic_past,
      l10n.topic_philosophy,
      l10n.topic_ethics_philosophy,
      l10n.topic_legal_news,
      l10n.topic_foreign_language,
      l10n.topic_legal_advice,
      l10n.topic_legal_advice_uk,
    ],
    l10n.category_sports: [
      l10n.topic_football,
      l10n.topic_realmadrid,
      l10n.topic_formula1,
      l10n.topic_superlig,
      l10n.topic_formula1TR,
      l10n.topic_motor_sports,
      l10n.topic_nba,
      l10n.topic_fenerbahce,
      l10n.topic_basketball,
      l10n.topic_wrestling_fighting,
    ],
    l10n.category_games: [
      l10n.topic_action_games,
      l10n.topic_ea_sports_fc,
      l10n.topic_clashroyale,
      l10n.topic_path_of_exile,
      l10n.topic_rpg,
      l10n.topic_cyberpunk,
      l10n.topic_game_news,
      l10n.topic_genshin,
      l10n.topic_strategy_games,
      l10n.topic_adventure_games,
    ],
    l10n.category_internet: [
      l10n.topic_tamamahbapengelli,
      l10n.topic_sacmabirsub,
      l10n.topic_bbaldiback,
      l10n.topic_funny,
      l10n.topic_memes,
      l10n.topic_interesting,
      l10n.topic_cringe_facepalm,
      l10n.topic_reddit_meta,
      l10n.topic_animals,
      l10n.topic_dewrim,
    ],
    l10n.category_travel: [
      l10n.topic_middle_east,
      l10n.topic_europe,
      l10n.topic_istanbul,
      l10n.topic_travel_vacation,
      l10n.topic_north_america,
      l10n.topic_europe_continent,
      l10n.topic_asia,
      l10n.topic_izmir,
      l10n.topic_travel_inspiration,
      l10n.topic_germany,
    ],
    l10n.category_qa: [
      l10n.topic_qa,
      l10n.topic_askturkey,
      l10n.topic_am_i_the_ahole,
      l10n.topic_am_i_overreacting,
      l10n.topic_no_stupid_questions,
      l10n.topic_advice,
    ],
  };
}




