const Map<String, List<String>> topicsData = {
  "İş Dünyası ve Finans": [
    "Hisse Senetleri ve Yatırım",
    "Bireysel Finans",
    "borsavefon",
    "Fırsatlar ve Pazar Yeri",
    "Emlak",
    "Finanzen",
    "İş Dünyasından Haberler ve Tartışmalar",
    "Kripto",
    "WallStreetBets",
    "Startup ve Girişimcilik",
  ],
  "Eğitim ve Kariyer": [
    "liseliler",
    "Okul ve Eğitim",
    "ODTU",
    "Kariyer",
    "YurtdisiUni",
    "turkishlearning",
    "Teaching",
    "remotework",
    "sysadmin",
    "jobs",
  ],
  "Beşeri Bilimler ve Hukuk": [
    "Kamalizm",
    "Hukuk",
    "TarihiSeyler",
    "Geçmiş",
    "felsefe",
    "Etik ve Felsefe",
    "Legal News & Discussion",
    "Yabancı Dil",
    "Legal advice",
    "Legal advice UK",
  ],
  "Spor": [
    "Futbol",
    "realmadrid",
    "Formula 1",
    "superlig",
    "formula1TR",
    "Motor Sporları",
    "NBA",
    "FenerbahceSK",
    "Basketbol",
    "Güreş ve Dövüş Sporları",
  ],
  "Oyunlar": [
    "Aksiyon Oyunları",
    "EA Sports FC",
    "ClashRoyale",
    "Path of Exile 2",
    "Rol Yapma Oyunları",
    "Cyberpunk 2077",
    "Oyun Haberleri ve Tartışmaları",
    "Genshin Impact",
    "Strateji Oyunları",
    "Macera Oyunları",
  ],
  "İnternet Kültürü": [
    "tamamahbapengelli",
    "SacmaBirSub",
    "bbaldiback",
    "Komik",
    "Meme'ler",
    "İlginç",
    "Cringe ve Facepalm",
    "Reddit Meta",
    "Hayvanlar ve Evcil Hayvanlar",
    "dewrim",
  ],
  "Gezilecek Yerler": [
    "Orta Doğu'daki Yerler",
    "Avrupa'daki Yerler",
    "istanbul",
    "Seyahat ve Tatil",
    "Kuzey Amerika'daki Yerler",
    "Europe",
    "Asya'daki Yerler",
    "Izmir",
    "Travel inspiration",
    "germany",
  ],
  "Soru-Cevap/Öykü": [
    "Soru-Cevap",
    "AskTurkey",
    "Am I the A**hole",
    "Am I Overreacting",
    "No Stupid Questions",
    "Advice",
  ],
};
